### ISSUE TITLE
Peer-to-Peer Code Review (The Sandpipers)

### ISSUE THREAD

**Issue by teekaytech** [ebeagusamuel/ror-social-scaffold#8]

**Comment by kubilaycaglayan** [comment]
Hello Taofeek, :hand: 

Thanks for presentation.

I think you can **strip all your methods that are about friendship requests from users controller and put them inside the requests controller**(I am not sure if you have the correct routes for it :thinking:  , but if you don't have I think that's another thing you should add). This way, everything will be in its own place. :star: 

With all my respect...

**Comment by teekaytech** [comment]
> Hello Taofeek, 
> 
> Thanks for presentation.
> 
> I think you can **strip all your methods that are about friendship requests from users controller and put them inside the requests controller**(I am not sure if you have the correct routes for it  , but if you don't have I think that's another thing you should add). This way, everything will be in its own place. 
> 
> With all my respect...

Thank you, Kubilay. It's appreciated. I'll look into it.

**Comment by mariosknl** [comment]
Great presentation Taofeek,

Both of you have done a great job on this project.

**Comment by teekaytech** [comment]
> Great presentation Taofeek,
> 
> Both of you have done a great job on this project.

Thanks, friend. Well appreciated.
